name: Deploy dictatorjs

on:
  release:
    types:
      - created

jobs:
  Release-Docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: connorhsmith/dictatorjs
          tags: |
            type=schedule
            type=semver,pattern={{version}}
            type=sha

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}, connorhsmith/dictatorjs:latest
          labels: ${{ steps.meta.outputs.labels }}

  Deploy-Production:
    needs:
      - Release-Docker
      - Deploy-Commands
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Deploy via webhook
        uses: joelwmale/webhook-action@master
        with:
          url: ${{ secrets.DEPLOY_WEBHOOK_URL }}

  Deploy-Commands:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Deploy commands
        run: node deploy-commands.js
        env:
          TOKEN: ${{ secrets.PROD_BOT_TOKEN }}
